{% set name = "beets" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beets-{{ version }}.tar.gz
  sha256: 9ca4a34a9aac0ccf36f3d80a96a92d037978c1bbf7231af28a899447f7abb651

build:
  entry_points:
    - beet = beets.ui:main
  skip: true  # [py>=400]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python
    - colorama
    - confuse >=2.1.0
    - jellyfish
    - lap >=0.5.12
    - mediafile >=0.12.0
    - numpy >=2.0.2  # [py<313]
    - numpy >=2.3.4  # [py>=313]
    - platformdirs >=3.5.0
    - pyyaml
    - requests >=2.32.5
    - requests-ratelimiter >=0.7.0
    - typing_extensions
    - unidecode >=1.3.6
    - scipy >=1.13.1  # [py<313]
    - scipy >=1.16.1  # [py>=313]
    - numba >=0.60  # [py<313]
    - numba >=0.62.1  # [py>=313]
    - packaging  # [py>=313]
  run_constrained:
    - beautifulsoup4 *
    - dbus-python *
    - flask *
    - flask-cors *
    - langdetect *
    - librosa >=0.11
    - mutagen >=1.33
    - Pillow *
    - py7zr *
    - pyacoustid *
    - PyGObject *
    - pylast *
    - python-mpd2 >=0.4.2
    - python3-discogs-client >=2.3.15
    - pyxdg *
    - rarfile *
    - reflink *
    - resampy >=0.4.3
    - requests-oauthlib >=0.6.1
    - soco *
    - docutils >=0.20.1
    - pydata-sphinx-theme *
    - sphinx *
    - sphinx-design >=0.6.1
    - sphinx-copybutton >=0.5.2
    - sphinx-toolbox >=4.1.0
    - titlecase >=2.4.1,<3.0.0
test:
  imports:
    - beets
    - beetsplug
  commands:
    - pip check
    - beet --help
  requires:
    - pip
    - python

about:
  home: https://beets.io/
  summary: music tagger and library organizer
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/beetbox/beets
  doc_url: https://beets.readthedocs.io/
  description: |
    Beets is the media library management system for obsessive music geeks.
    The purpose of beets is to get your music collection right once and for all. 
    It catalogs your collection, automatically improving its metadata as it goes. 
    It then provides a bouquet of tools for manipulating and accessing your music.

extra:
  recipe-maintainers:
    - HeavyTony2
