{% set name = "beets" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beets-{{ version }}.tar.gz
  sha256: a0abcdf95d5f89fcf46b07ddc2b5b92e1dd5abe68f4cc7222f21aff2dffc4789

build:
  entry_points:
    - beet = beets.ui:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - unidecode >=1.3.6
    - musicbrainzngs >=0.4
    - pyyaml
    - mediafile >=0.12.0
    - confuse >=1.5.0
    - munkres >=1.0.0
    - jellyfish
    - colorama
    - typing-extensions
    - platformdirs >=3.5.0
  run_constrained:
    - beautifulsoup4 *
    - dbus-python *
    - flask *
    - flask-cors *
    - langdetect *
    - librosa >=0.10.2,<0.10.3
    - mutagen >=1.33
    - Pillow *
    - py7zr *
    - pyacoustid *
    - PyGObject *
    - pylast *
    - python-mpd2 >=0.4.2
    - python3-discogs-client >=2.3.15
    - pyxdg *
    - rarfile *
    - reflink *
    - requests *
    - resampy >=0.4.3
    - requests-oauthlib >=0.6.1
    - soco *
    - pydata-sphinx-theme *
    - sphinx *
test:
  imports:
    - beets
    - beetsplug
  commands:
    - pip check
    - beet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://beets.io/
  summary: music tagger and library organizer
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/beetbox/beets
  doc_url: https://beets.readthedocs.io/


extra:
  recipe-maintainers:
    - HeavyTony2
