{% set name = "beets" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beets-{{ version }}.tar.gz
  sha256: 7f12cce3d5c3bfd68144407e86ae7fbaada6dc41676a49ab42027e156bdcfb73

build:
  entry_points:
    - beet = beets.ui:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - colorama
    - confuse >=1.5.0
    - jellyfish
    - lap >=0.5.12
    - mediafile >=0.12.0
    - musicbrainzngs >=0.4
    - numpy >=1.24.4
    - platformdirs >=3.5.0
    - pyyaml
    - typing_extensions
    - unidecode >=1.3.6
  run_constrained:
    - beautifulsoup4 *
    - dbus-python *
    - flask *
    - flask-cors *
    - langdetect *
    - librosa >=0.10.2.post1,<0.11.0
    - mutagen >=1.33
    - Pillow *
    - py7zr *
    - pyacoustid *
    - PyGObject *
    - pylast *
    - python-mpd2 >=0.4.2
    - python3-discogs-client >=2.3.15
    - pyxdg *
    - rarfile *
    - reflink *
    - requests *
    - resampy >=0.4.3
    - requests-oauthlib >=0.6.1
    - soco *
    - pydata-sphinx-theme *
    - sphinx *
test:
  imports:
    - beets
    - beetsplug
  commands:
    - pip check
    - beet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://beets.io/
  summary: music tagger and library organizer
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/beetbox/beets
  doc_url: https://beets.readthedocs.io/
  description: |
    Beets is the media library management system for obsessive music geeks.
    The purpose of beets is to get your music collection right once and for all. 
    It catalogs your collection, automatically improving its metadata as it goes. 
    It then provides a bouquet of tools for manipulating and accessing your music.

extra:
  recipe-maintainers:
    - HeavyTony2
