schema_version: 1

context:
  name: beets
  version: "2.6.2"
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/beets-${{ version }}.tar.gz
  sha256: 90b900f92b105cce6fa3a06160e025315fc3716f3733083894e4aae289008e82

build:
  number: ${{ build_number }}
  string: python_min${{ python_min }}_pyh${{ hash }}_${{ build_number }}
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - beet = beets.ui:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - colorama
    - confuse >=2.1.0
    - jellyfish
    - lap >=0.5.12
    - mediafile >=0.12.0
    - numpy >=${{ numpy_min }}
    - packaging >=24.0
    - platformdirs >=3.5.0
    - pyyaml
    - requests >=2.32.5
    - requests-ratelimiter >=0.7.0
    - typing_extensions
    - unidecode >=1.3.6
    - scipy >=${{ scipy_min }}
    - numba >=${{ numba_min }}
  run_constraints:
    - beautifulsoup4 *
    - dbus-python *
    - flask *
    - flask-cors *
    - langdetect *
    - librosa >=0.11
    - mutagen >=1.33
    - Pillow *
    - py7zr *
    - pyacoustid *
    - PyGObject *
    - pylast *
    - python-mpd2 >=0.4.2
    - python3-discogs-client >=2.3.15
    - pyxdg *
    - rarfile *
    - reflink *
    - resampy >=0.4.3
    - requests-oauthlib >=0.6.1
    - soco *
    - docutils >=0.20.1
    - pydata-sphinx-theme *
    - sphinx *
    - sphinx-design >=0.6.1
    - sphinx-copybutton >=0.5.2
    - sphinx-toolbox >=4.1.0
    - titlecase >=2.4.1,<3.0.0

tests:
  - python:
      imports:
        - beets
        - beetsplug
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - beet --help

about:
  summary: music tagger and library organizer
  license: MIT
  license_file: LICENSE
  description: |
    Beets is the media library management system for obsessive music geeks.
    The purpose of beets is to get your music collection right once and for all.
    It catalogs your collection, automatically improving its metadata as it goes.
    It then provides a bouquet of tools for manipulating and accessing your music.


  homepage: https://beets.io/
  repository: https://github.com/beetbox/beets
  documentation: https://beets.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
